"""Add enhanced company and customer details

Revision ID: 1d8f81efbf19
Revises: 
Create Date: 2026-05-03 08:09:02.740287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d8f81efbf19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip ALTER COLUMN operations for SQLite compatibility
    # Only add new columns and create indexes
    op.add_column('companies', sa.Column('vrn_no', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('tin_no', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('website', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('physical_address', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('postal_address', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('country', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('region', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('city', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('business_license_no', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('business_registration_no', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('business_type', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('year_established', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('contact_person', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('contact_person_title', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('alternative_phone', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('fax', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('whatsapp', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('facebook', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('twitter', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('instagram', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('linkedin', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('document_prefix', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('document_footer', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('document_header', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('customer_number', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('tax_id', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('vrn_no', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('physical_address', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('postal_address', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('country', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('region', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('city', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('business_name', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('business_type', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('contact_person', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('contact_person_title', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('website', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('shipping_address', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('shipping_city', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('shipping_region', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('shipping_country', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('shipping_postal_code', sa.String(), nullable=True))
    
    # Create new tables for bank details and terms conditions
    op.create_table('company_bank_details',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('company_id', sa.String(), nullable=False),
        sa.Column('bank_name', sa.String(), nullable=False),
        sa.Column('account_name', sa.String(), nullable=False),
        sa.Column('account_number', sa.String(), nullable=False),
        sa.Column('branch_name', sa.String(), nullable=True),
        sa.Column('branch_code', sa.String(), nullable=True),
        sa.Column('swift_code', sa.String(), nullable=True),
        sa.Column('iban', sa.String(), nullable=True),
        sa.Column('routing_number', sa.String(), nullable=True),
        sa.Column('sort_code', sa.String(), nullable=True),
        sa.Column('bank_address', sa.Text(), nullable=True),
        sa.Column('is_primary', sa.Boolean(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id']),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('company_terms_conditions',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('company_id', sa.String(), nullable=False),
        sa.Column('document_type', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('terms_text', sa.Text(), nullable=True),
        sa.Column('payment_terms', sa.Text(), nullable=True),
        sa.Column('delivery_terms', sa.Text(), nullable=True),
        sa.Column('warranty_terms', sa.Text(), nullable=True),
        sa.Column('return_policy', sa.Text(), nullable=True),
        sa.Column('late_payment_terms', sa.Text(), nullable=True),
        sa.Column('cancellation_policy', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id']),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes
    op.create_index(op.f('ix_product_batches_company_id'), 'product_batches', ['company_id'], unique=False)
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes first
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_index(op.f('ix_product_batches_company_id'), table_name='product_batches')
    
    # Drop new tables
    op.drop_table('company_terms_conditions')
    op.drop_table('company_bank_details')
    
    # Drop columns from customers
    op.drop_column('customers', 'shipping_postal_code')
    op.drop_column('customers', 'shipping_country')
    op.drop_column('customers', 'shipping_region')
    op.drop_column('customers', 'shipping_city')
    op.drop_column('customers', 'shipping_address')
    op.drop_column('customers', 'website')
    op.drop_column('customers', 'contact_person_title')
    op.drop_column('customers', 'contact_person')
    op.drop_column('customers', 'business_type')
    op.drop_column('customers', 'business_name')
    op.drop_column('customers', 'postal_code')
    op.drop_column('customers', 'city')
    op.drop_column('customers', 'region')
    op.drop_column('customers', 'country')
    op.drop_column('customers', 'postal_address')
    op.drop_column('customers', 'physical_address')
    op.drop_column('customers', 'vrn_no')
    op.drop_column('customers', 'tax_id')
    op.drop_column('customers', 'customer_number')
    
    # Drop columns from companies
    op.drop_column('companies', 'document_header')
    op.drop_column('companies', 'document_footer')
    op.drop_column('companies', 'document_prefix')
    op.drop_column('companies', 'linkedin')
    op.drop_column('companies', 'instagram')
    op.drop_column('companies', 'twitter')
    op.drop_column('companies', 'facebook')
    op.drop_column('companies', 'whatsapp')
    op.drop_column('companies', 'fax')
    op.drop_column('companies', 'alternative_phone')
    op.drop_column('companies', 'contact_person_title')
    op.drop_column('companies', 'contact_person')
    op.drop_column('companies', 'year_established')
    op.drop_column('companies', 'industry')
    op.drop_column('companies', 'business_type')
    op.drop_column('companies', 'business_registration_no')
    op.drop_column('companies', 'business_license_no')
    op.drop_column('companies', 'postal_code')
    op.drop_column('companies', 'city')
    op.drop_column('companies', 'region')
    op.drop_column('companies', 'country')
    op.drop_column('companies', 'postal_address')
    op.drop_column('companies', 'physical_address')
    op.drop_column('companies', 'website')
    op.drop_column('companies', 'tin_no')
    op.drop_column('companies', 'vrn_no')
    
    # Skip ALTER COLUMN operations for SQLite compatibility
    # ### end Alembic commands ###
