"""init tables

Revision ID: 8a0a68426d10
Revises: 1d8f81efbf19
Create Date: 2026-05-05 09:05:23.526419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a0a68426d10'
down_revision: Union[str, Sequence[str], None] = '1d8f81efbf19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advertisements', 'media_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'image'"))
    op.alter_column('companies', 'authorised_signatory',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('company_bank_details', 'mobile_money_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('company_bank_details', 'mobile_money_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('product_batches', 'company_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_product_batches_company_id'), 'product_batches', ['company_id'], unique=False)
    op.alter_column('products', 'barcode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.alter_column('transactions', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'sale'"))
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.alter_column('transactions', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'sale'"))
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.alter_column('products', 'barcode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_product_batches_company_id'), table_name='product_batches')
    op.alter_column('product_batches', 'company_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('company_bank_details', 'mobile_money_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('company_bank_details', 'mobile_money_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('companies', 'authorised_signatory',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('advertisements', 'media_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'image'"))
    # ### end Alembic commands ###
